import React, { useState } from 'react';

function Info({ label, value }) { return <div className="kp-card-soft p-4"><p className="text-[10px] uppercase font-bold text-[#7a8aa7]">{label}</p><p className="text-sm font-bold text-white mt-1">{value || 'Add detail'}</p></div>; }

export default function AthleteProfileTab({ athlete, onUpdateProfile }) {
  const [visibility, setVisibility] = useState('Scouts only');
  const [saved, setSaved] = useState(false);
  const completion = [athlete.fullName, athlete.age, athlete.location, athlete.primarySport, athlete.position].filter(Boolean).length * 20;
  const update = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onUpdateProfile({ fullName: form.get('fullName'), location: form.get('location'), primarySport: form.get('primarySport'), position: form.get('position') }); setSaved(true); }; 
  return <div className="space-y-6">
    <div className="kp-card kp-card-hoverable p-6 border-l-4 border-l-[#d4ff4d]"><div className="flex flex-col md:flex-row md:items-center gap-5"><div className="w-24 h-24 rounded-2xl bg-gradient-to-br from-[#16304a] to-[#0f1c2d] border border-[#74c9ff]/30 flex items-center justify-center text-4xl font-black text-[#74c9ff]">{athlete.fullName?.[0] || 'A'}</div><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><span className="kp-pill active">Verified athlete</span><span className="kp-pill">{athlete.primarySport}</span></div><h2 className="text-3xl font-black text-white mt-2">{athlete.fullName}</h2><p className="text-sm text-[#a1afc7]">{athlete.age} yrs · {athlete.gender} · {athlete.location}</p><p className="text-sm text-[#a1afc7] mt-2 max-w-2xl">Explosive multi-sport athlete building a verified performance profile through computer-vision assessments and competition results.</p></div><button onClick={() => document.getElementById('athlete-profile-form')?.scrollIntoView({ behavior: 'smooth' })} className="kp-button py-2.5 px-5 text-sm">Edit Profile</button></div><div className="mt-5"><div className="flex justify-between text-xs text-[#a1afc7] mb-1"><span>Profile completion</span><span className="text-[#d4ff4d]">{completion}%</span></div><div className="h-2 bg-[#0b1220] rounded-full overflow-hidden"><div className="h-full bg-[#d4ff4d]" style={{ width: `${completion}%` }} /></div></div></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Info label="Current team / club" value="Independent athlete" /><Info label="Experience" value="Youth competitive" /><Info label="Dominant foot" value="Right" /><Info label="Nationality" value="India" /></div>
    <div className="grid lg:grid-cols-2 gap-5"><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Athlete information</div><h3 className="text-xl font-black text-white mb-4">Sport CV</h3><div className="grid grid-cols-2 gap-3"><Info label="Preferred position" value={athlete.position || 'Long jump specialist'} /><Info label="Coach" value="Add coach details" /><Info label="Height" value="Add height" /><Info label="Weight" value="Add weight" /></div></div><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Privacy & visibility</div><h3 className="text-xl font-black text-white mb-4">Who can view your profile?</h3><select value={visibility} onChange={(event) => setVisibility(event.target.value)} className="kp-select"><option>Public profile</option><option>Scouts only</option><option>Private profile</option></select><p className="text-xs text-[#7a8aa7] mt-3">Assessment metrics and videos follow this visibility setting.</p></div></div>
    <div id="athlete-profile-form" className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Profile editor</div><h3 className="text-xl font-black text-white mb-4">Keep your scouting profile current</h3>{saved && <p className="kp-status-success p-3 rounded-lg text-xs mb-3">Profile saved successfully.</p>}<form onSubmit={update} className="grid md:grid-cols-2 gap-3"><input name="fullName" defaultValue={athlete.fullName} className="kp-input" placeholder="Full name" /><input name="location" defaultValue={athlete.location} className="kp-input" placeholder="Location" /><input name="primarySport" defaultValue={athlete.primarySport} className="kp-input" placeholder="Primary sport" /><input name="position" defaultValue={athlete.position} className="kp-input" placeholder="Position / role" /><button className="kp-button py-3 md:col-span-2">Save Profile</button></form></div>
    <div className="grid md:grid-cols-2 gap-5"><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Media library</div><h3 className="text-xl font-black text-white">Highlights & training</h3><p className="text-sm text-[#a1afc7] mt-2">Upload match highlights, training clips, and skill demonstrations for scouts.</p><label className="kp-button inline-block mt-4 py-2.5 px-4 text-sm cursor-pointer">Upload video<input type="file" accept="video/*" className="hidden" /></label></div><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Documents</div><h3 className="text-xl font-black text-white">Certificates & clearances</h3><p className="text-sm text-[#a1afc7] mt-2">Keep verification documents ready for opportunity applications.</p><label className="kp-button inline-block mt-4 py-2.5 px-4 text-sm cursor-pointer">Upload document<input type="file" accept=".pdf,image/*" className="hidden" /></label></div></div>
  </div>;
}
