import React, { useMemo, useState } from 'react';
import AppIcon from '../ui/AppIcon';
import { getAllProfiles, getAthleteAssessments } from '../../lib/auth';

function AthleteXLogo() {
  return (
    <svg viewBox="0 0 92 92" className="kp-brand-logo-svg" aria-hidden="true">
      <defs>
        <linearGradient id="athletex-blue-workspace" x1="0%" x2="100%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#7be3ff" />
          <stop offset="45%" stopColor="#2fb5ff" />
          <stop offset="100%" stopColor="#1788ff" />
        </linearGradient>
      </defs>
      <path d="M19 70L44 16H51L72 70H60L54 55H41L35 70H19ZM43 47H52L47 33L43 47Z" fill="url(#athletex-blue-workspace)" />
      <path d="M30 63L48 42L59 55L64 50L84 71L75 80L55 60L44 72L30 63Z" fill="url(#athletex-blue-workspace)" opacity="0.9"/>
      <path d="M48 25L41 36H54L48 25Z" fill="#09233a" opacity="0.8"/>
      <path d="M18 20C28 25 32 31 36 40C26 46 18 52 12 60C10 42 11 30 18 20Z" fill="#0d2948" opacity="0.9"/>
      <circle cx="49" cy="22" r="5" fill="#0b1c2d" opacity="0.8"/>
      <path d="M43 30C47 30 49 31 52 33C53 39 53 46 50 52C48 49 46 47 43 45C42 39 42 34 43 30Z" fill="#0b1c2d" opacity="0.8"/>
    </svg>
  );
}

const getStorageKey = (scoutId, suffix) => `sports_talent_scout_${scoutId}_${suffix}`;

const STAGES = ['Discovered', 'Reviewing', 'Shortlisted', 'Under Evaluation', 'Contacted', 'Trial Invited'];

function getSavedAthletes() {
  return getAllProfiles().filter((profile) => profile.role !== 'scout').map((profile) => {
    const assessments = getAthleteAssessments(profile.id);
    const latest = assessments[0]?.resultData?.metrics || {};
    const rating = latest.technique_score || latest.measurement_confidence || latest.detection_confidence || 0;
    return { id: profile.id, name: profile.fullName, sport: profile.primarySport, position: profile.position || 'Athlete', age: profile.age, location: profile.location, team: profile.currentTeam || 'Independent athlete', rating: Math.round(rating), speed: latest.approach_velocity_mps || '--', strength: '--', skill: latest.technique_score || '--', stage: 'Discovered', verified: assessments.length > 0 };
  });
}

function Metric({ label, value, color = 'text-white' }) { return <div className="kp-card-soft p-4"><p className="text-[10px] uppercase font-bold text-[#7a8aa7]">{label}</p><p className={`text-2xl font-black mt-1 ${color}`}>{value}</p></div>; }
function AthleteCard({ athlete, shortlisted, onShortlist, onEvaluate }) {
  return <div className="kp-card-soft p-4 space-y-3">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-full bg-[#16304a] text-[#74c9ff] flex items-center justify-center font-black">{athlete.name[0]}</div><div><p className="font-bold text-white">{athlete.name}</p><p className="text-xs text-[#a1afc7]">{athlete.position} · {athlete.sport}</p></div></div><span className="kp-pill active">{athlete.rating}/100</span></div>
    <div className="grid grid-cols-3 gap-2 text-xs"><div><span className="text-[#7a8aa7]">Age</span><p className="text-white font-bold">{athlete.age}</p></div><div><span className="text-[#7a8aa7]">Location</span><p className="text-white font-bold">{athlete.location}</p></div><div><span className="text-[#7a8aa7]">Status</span><p className="text-emerald-300 font-bold">{athlete.verified ? 'Verified' : 'Pending'}</p></div></div>
    <div className="flex gap-2"><button onClick={onEvaluate} className="kp-button flex-1 py-2 text-xs">View & Evaluate</button><button onClick={onShortlist} className={`flex-1 py-2 text-xs rounded-lg border font-bold ${shortlisted ? 'border-[#d4ff4d] text-[#d4ff4d]' : 'border-[#1d2a3d] text-[#a1afc7]'}`}>{shortlisted ? <><AppIcon name="star" size={14} /> Shortlisted</> : <><AppIcon name="star" size={14} /> Shortlist</>}</button></div>
  </div>;
}

export default function ScoutWorkspace({ scout, onLogout }) {
  const athletes = useMemo(() => getSavedAthletes(), []);
  const [activeTab, setActiveTab] = useState('overview');
  const [query, setQuery] = useState('');
  const [sport, setSport] = useState('All sports');
  const [shortlist, setShortlistState] = useState(() => {
    if (typeof window === 'undefined') return [];
    try { return JSON.parse(localStorage.getItem(getStorageKey(scout.id, 'shortlist')) || '[]'); } catch { return []; }
  });
  const [stages, setStages] = useState(() => {
    if (typeof window === 'undefined') return Object.fromEntries(athletes.map((athlete) => [athlete.id, athlete.stage]));
    try { return { ...Object.fromEntries(athletes.map((athlete) => [athlete.id, athlete.stage])), ...JSON.parse(localStorage.getItem(getStorageKey(scout.id, 'stages')) || '{}') }; } catch { return Object.fromEntries(athletes.map((athlete) => [athlete.id, athlete.stage])); }
  });
  const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => athletes.filter((athlete) => (!query || `${athlete.name} ${athlete.position} ${athlete.location}`.toLowerCase().includes(query.toLowerCase())) && (sport === 'All sports' || athlete.sport === sport)), [athletes, query, sport]);
  const persist = (suffix, value) => { if (typeof window !== 'undefined') localStorage.setItem(getStorageKey(scout.id, suffix), JSON.stringify(value)); };
  const setShortlist = (updater) => setShortlistState((current) => { const next = typeof updater === 'function' ? updater(current) : updater; persist('shortlist', next); return next; });
  const move = (id, direction) => { const index = STAGES.indexOf(stages[id]); const next = STAGES[Math.max(0, Math.min(STAGES.length - 1, index + direction))]; setStages((current) => { const updated = { ...current, [id]: next }; persist('stages', updated); return updated; }); };
  const nav = [{ id: 'overview', label: 'Dashboard', icon: 'chart' }, { id: 'discover', label: 'Discover Athletes', icon: 'search' }, { id: 'shortlist', label: 'Shortlist', icon: 'star' }, { id: 'pipeline', label: 'Pipeline', icon: 'pipeline' }, { id: 'evaluations', label: 'Evaluations', icon: 'note' }, { id: 'opportunities', label: 'Opportunities', icon: 'target' }, { id: 'team', label: 'Team Members', icon: 'users' }, { id: 'analytics', label: 'Analytics', icon: 'trend' }];
  return <div className="kp-shell min-h-screen flex flex-col"><header className="bg-[#070d18] border-b border-[#1d2a3d] sticky top-0 z-40"><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="flex items-center justify-between min-h-16 gap-4"><div className="flex items-center gap-3"><div className="kp-brand-mark" style={{ width: 48, height: 48, borderRadius: 14 }}><AthleteXLogo /></div><div className="kp-brand-stack" style={{ transform: 'translateY(-1px)' }}><h1 className="kp-brand-name text-base" style={{ fontSize: '1.02rem' }}>AthleteX</h1><p className="kp-brand-sub" style={{ fontSize: '0.46rem', letterSpacing: '0.18em' }}>Recruitment Intelligence</p></div></div><div className="hidden md:block text-right text-xs"><p className="font-bold text-white">{scout.fullName}</p><p className="text-[10px] text-[#7a8aa7]">{scout.organizationName || 'Scouting team'} · {scout.recruiterId || 'Recruiter ID not provided'}</p></div><button onClick={onLogout} title="Sign out" className="text-[#7a8aa7] hover:text-[#ffb4c1]"><AppIcon name="x" size={15} /></button></div><nav className="flex gap-1 overflow-x-auto py-2 border-t border-[#1d2a3d]/50 no-scrollbar">{nav.map((item) => <button key={item.id} onClick={() => setActiveTab(item.id)} className={`px-2.5 py-1.5 text-[11px] font-bold rounded-md whitespace-nowrap ${activeTab === item.id ? 'bg-[#0f1c2d] text-[#74c9ff] border border-[#74c9ff]/30' : 'text-[#a1afc7]'}`}><AppIcon name={item.icon} size={14} /> {item.label}</button>)}</nav></div></header>
    <main className="max-w-7xl mx-auto w-full px-4 sm:px-6 py-6 flex-1 space-y-6">
      {activeTab === 'overview' && <><div className="kp-card kp-card-hoverable p-6 border-l-4 border-l-[#74c9ff]"><div className="kp-kicker">Scouting Operations</div><h2 className="text-3xl font-black text-white mt-1">Recruitment command center</h2><p className="text-sm text-[#a1afc7] mt-2">Find high-potential athletes, record evaluations, and move prospects through your pipeline.</p></div><div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Metric label="Discovered" value={athletes.length} /><Metric label="Shortlisted" value={shortlist.length} color="text-[#d4ff4d]" /><Metric label="Evaluating" value={Object.values(stages).filter((stage) => stage === 'Under Evaluation').length} color="text-[#74c9ff]" /><Metric label="Opportunities" value="6" /><Metric label="Conversion" value={athletes.length ? `${Math.round(shortlist.length / athletes.length * 100)}%` : '0%'} color="text-emerald-300" /></div><div className="grid lg:grid-cols-[1.4fr_1fr] gap-5"><div className="kp-card kp-card-hoverable p-5"><div className="flex justify-between items-center mb-4"><div><div className="kp-kicker">Priority prospects</div><h3 className="text-xl font-black text-white">Shortlist review</h3></div><button onClick={() => setActiveTab('shortlist')} className="text-xs text-[#74c9ff]">View all →</button></div><div className="space-y-3">{athletes.filter((athlete) => shortlist.includes(athlete.id)).map((athlete) => <AthleteCard key={athlete.id} athlete={athlete} shortlisted onShortlist={() => setShortlist((current) => current.filter((id) => id !== athlete.id))} onEvaluate={() => setSelected(athlete)} />)}{!shortlist.length && <p className="text-sm text-[#a1afc7]">No saved athletes yet.</p>}</div></div><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Activity</div><h3 className="text-xl font-black text-white mb-4">Team pulse</h3><div className="space-y-4 text-sm"><p className="text-[#a1afc7]">Registered athletes <strong className="float-right text-white">{athletes.length}</strong></p><p className="text-[#a1afc7]">Evaluations due <strong className="float-right text-yellow-300">{Object.values(stages).filter((stage) => stage === 'Under Evaluation').length}</strong></p><p className="text-[#a1afc7]">Shortlisted prospects <strong className="float-right text-[#74c9ff]">{shortlist.length}</strong></p></div></div></div></>}
      {activeTab === 'discover' && <><div className="kp-card kp-card-hoverable p-5"><div className="kp-kicker">Athlete Discovery</div><h2 className="text-2xl font-black text-white">Find your next prospect</h2><div className="grid sm:grid-cols-[1fr_180px] gap-3 mt-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, position, location" className="kp-input" /><select value={sport} onChange={(event) => setSport(event.target.value)} className="kp-select"><option>All sports</option><option>Track & Field</option><option>Basketball</option><option>Football</option></select></div></div><div className="grid md:grid-cols-2 gap-4">{filtered.map((athlete) => <AthleteCard key={athlete.id} athlete={athlete} shortlisted={shortlist.includes(athlete.id)} onShortlist={() => setShortlist((current) => current.includes(athlete.id) ? current.filter((id) => id !== athlete.id) : [...current, athlete.id])} onEvaluate={() => setSelected(athlete)} />)}</div>{filtered.length === 0 && <div className="kp-card kp-card-hoverable p-10 text-center text-[#a1afc7]">No athletes match these filters.</div>}</>}
      {activeTab === 'shortlist' && <><div><div className="kp-kicker">Shortlist</div><h2 className="text-2xl font-black text-white">Priority athletes</h2></div><div className="grid md:grid-cols-2 gap-4">{athletes.filter((athlete) => shortlist.includes(athlete.id)).map((athlete) => <AthleteCard key={athlete.id} athlete={athlete} shortlisted onShortlist={() => setShortlist((current) => current.filter((id) => id !== athlete.id))} onEvaluate={() => setSelected(athlete)} />)}</div></>}
      {activeTab === 'pipeline' && <div><div className="kp-kicker">Recruitment Pipeline</div><h2 className="text-2xl font-black text-white mb-4">Move prospects forward</h2><div className="grid md:grid-cols-3 xl:grid-cols-6 gap-3">{STAGES.map((stage) => <div key={stage} className="kp-card kp-card-hoverable p-3 min-h-44"><p className="text-xs font-bold text-[#a1afc7] uppercase mb-3">{stage}</p>{athletes.filter((athlete) => stages[athlete.id] === stage).map((athlete) => <div key={athlete.id} className="kp-card-soft p-3 mb-2"><p className="text-sm font-bold text-white">{athlete.name}</p><p className="text-[11px] text-[#7a8aa7]">{athlete.position} · {athlete.rating || '--'}/100</p><div className="flex gap-1 mt-2"><button onClick={() => move(athlete.id, -1)} className="text-xs text-[#7a8aa7]">←</button><button onClick={() => move(athlete.id, 1)} className="text-xs text-[#74c9ff]">→</button></div></div>)}</div>)}</div></div>}
      {activeTab === 'evaluations' && <div className="kp-card kp-card-hoverable p-6"><div className="kp-kicker">Evaluation Desk</div><h2 className="text-2xl font-black text-white mb-2">Pending evaluations</h2><p className="text-sm text-[#a1afc7] mb-5">Score technical ability, physical profile, mentality, consistency, and potential with private notes.</p><div className="space-y-3">{athletes.filter((athlete) => stages[athlete.id] === 'Under Evaluation' || shortlist.includes(athlete.id)).map((athlete) => <button key={athlete.id} onClick={() => setSelected(athlete)} className="kp-card-soft w-full p-4 flex justify-between text-left"><span className="text-white font-bold">{athlete.name}<span className="block text-xs text-[#7a8aa7]">{athlete.position} · Last reviewed today</span></span><span className="text-[#d4ff4d] font-black">{athlete.rating || '--'}/100 →</span></button>)}</div></div>}
      {activeTab === 'opportunities' && <div className="kp-card kp-card-hoverable p-6"><div className="kp-kicker">Open Opportunities</div><h2 className="text-2xl font-black text-white mb-4">Active recruitment briefs</h2><div className="grid md:grid-cols-2 gap-3">{['U-18 Long Jump Development Camp', 'Women’s Basketball Guard Intake', 'Elite Football Academy Trials', 'Regional Sprint Scholarship'].map((title, index) => <div key={title} className="kp-card-soft p-4"><span className="kp-pill active">{index + 3} places</span><h3 className="text-white font-bold mt-3">{title}</h3><p className="text-xs text-[#a1afc7] mt-1">India · Applications close {12 + index} Sep 2026</p><button className="kp-button mt-4 py-2 px-4 text-xs">Review Applicants</button></div>)}</div></div>}
      {(activeTab === 'team' || activeTab === 'analytics') && <div className="kp-card kp-card-hoverable p-6"><div className="kp-kicker">{activeTab === 'team' ? 'Team Members' : 'Scouting Analytics'}</div><h2 className="text-2xl font-black text-white">{activeTab === 'team' ? 'Your scouting team' : 'Recruitment intelligence'}</h2><p className="text-sm text-[#a1afc7] mt-2">{activeTab === 'team' ? 'Manage assignments and permissions for your evaluation team.' : `Average athlete rating ${athletes.length ? Math.round(athletes.reduce((sum, athlete) => sum + athlete.rating, 0) / athletes.length) : '--'} · ${athletes.length} registered athlete(s) in your workspace.`}</p><div className="kp-card-soft p-4 mt-5"><p className="font-bold text-white">{scout.fullName}</p><p className="text-xs text-[#7a8aa7]">Lead Recruiter · {scout.location || 'Organization location'} · {athletes.length} athletes evaluated</p></div></div>}
    </main>
    {selected && <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4" onClick={() => setSelected(null)}><div className="kp-card kp-card-hoverable p-6 max-w-lg w-full" onClick={(event) => event.stopPropagation()}><div className="flex justify-between"><div><div className="kp-kicker">Private evaluation</div><h2 className="text-2xl font-black text-white">{selected.name}</h2><p className="text-sm text-[#a1afc7]">{selected.position} · {selected.team}</p></div><button onClick={() => setSelected(null)} className="text-[#7a8aa7]"><AppIcon name="x" size={15} /></button></div><div className="grid grid-cols-3 gap-3 mt-5"><Metric label="Overall" value={`${selected.rating}/100`} color="text-[#d4ff4d]" /><Metric label="Speed" value={selected.speed} color="text-[#74c9ff]" /><Metric label="Skill" value={selected.skill} /></div><label className="block text-xs text-[#a1afc7] mt-5">Scout notes<textarea className="kp-input mt-1 min-h-24" placeholder="Strengths, risks, recommendation..." /></label><div className="flex gap-3 mt-5"><button onClick={() => { setStages((current) => ({ ...current, [selected.id]: 'Under Evaluation' })); setSelected(null); }} className="kp-button flex-1 py-3">Save Evaluation</button><button onClick={() => setSelected(null)} className="kp-button-ghost px-4">Close</button></div></div></div>}
  </div>;
}
